"""Model-side experimental branches for the reproduction project."""

from .exact_hardmax import (
    config_for_operations,
    DecodeObservation,
    DecodeRun,
    LatestWriteDecodeConfig,
    MemoryOperation,
    encode_latest_write_key,
    encode_latest_write_query,
    extract_memory_operations,
    extract_stack_slot_operations,
    run_latest_write_decode,
    run_latest_write_decode_for_events,
    run_latest_write_decode_for_stack_events,
)
from .trainable_latest_write import (
    EvaluationResult,
    FitResult,
    LatestWriteCandidate,
    LatestWriteSample,
    TrainableLatestWriteScorer,
    build_countdown_stack_samples,
    build_dynamic_memory_stack_samples,
    evaluate_scorer,
    fit_scorer,
)

__all__ = [
    "config_for_operations",
    "DecodeObservation",
    "DecodeRun",
    "LatestWriteDecodeConfig",
    "LatestWriteCandidate",
    "LatestWriteSample",
    "MemoryOperation",
    "EvaluationResult",
    "FitResult",
    "TrainableLatestWriteScorer",
    "build_countdown_stack_samples",
    "build_dynamic_memory_stack_samples",
    "encode_latest_write_key",
    "encode_latest_write_query",
    "evaluate_scorer",
    "extract_memory_operations",
    "extract_stack_slot_operations",
    "fit_scorer",
    "run_latest_write_decode",
    "run_latest_write_decode_for_events",
    "run_latest_write_decode_for_stack_events",
]
